---
title: "Know your data"
author: "Sara Hänzi"
date: "2023-02-26"
output: 
  html_document:
    theme:
      version: 5
      bootswatch: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(dplyr)
library(markdown)
library(ggplot2)
library(thematic)
```

```{r}
ggplot2::theme_set(ggplot2::theme_gray(base_size = 16))
thematic::thematic_rmd()
```

```{r}
devtools::load_all()
```

Zurich plot 2022

```{r}
zh %>% 
  filter(year == 2022) %>% 
  heatmap_tod_date()
```

Winterthur 2022 fixed

```{r}
wi %>% 
  filter(year == 2022) %>% 
  heatmap_tod_date()
```

original
```{r}
wi %>% 
  mutate(timestamp_hours_only = timestamp_utc) %>%
    dplyr::mutate(timestamp_hours_only = stats::update(timestamp_hours_only,
                                         year = 2000,
                                         month = 1,
                                         day = 1)) %>% 
  filter(year == 2022) %>% 
  heatmap_tod_date()
```

