name: Update data

on:
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    #env:
      #GITHUB_PAT: ${{ secrets.PAT}}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("curl", "data.table", "dplyr", "fable",
          "fabletools", "feasts", "glue", "htmltools", "janitor", "lubridate",
          "magrittr", "purrr", "tidyr", "tsibble", "usethis"))
        shell: Rscript {0}

      - name: Update data
        run: |
          library(magrittr)
          source("R/utils_data_wrangle.R")
          source("R/utils_get_data.R")
          source("R/utils_module_dataviz.R")
          source("R/utils_module_overview_month.R")
          source("R/utils_module_overview_week.R")
          source("R/utils_module_overview_year.R")
          source("R/utils_module_predictions.R")
          source("R/utils_module_zh_details.R")
          load("data/zh_old.rda")
          load("data/wi_old.rda")
          source("data-raw/02_get_updated_data.R")
          source("data-raw/03_prepare_data_for_modules.R")
        shell: Rscript {0}

      - name: Git Commit/Push Changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.PAT }}
          push-branch: main
          name: GitHub Action Bot
          email: ${{ github.actor }}@localhost
          commit-message: Update with latest data
          rebase: 'true'
