name: Update data

on:
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT}}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("curl", "data.table", "dplyr", "fable",
          "fabletools", "feasts", "glue", "htmltools", "janitor", "lubridate",
          "magrittr", "purrr", "tidyr", "tsibble", "usethis"))
        shell: Rscript {0}

      - name: Update data
        run: |
          library(magrittr)
          source("R/utils_data_wrangle.R")
          source("R/utils_get_data.R")
          source("R/utils_module_dataviz.R")
          source("R/utils_module_overview_month.R")
          source("R/utils_module_overview_week.R")
          source("R/utils_module_overview_year.R")
          source("R/utils_module_predictions.R")
          source("R/utils_module_zh_details.R")
          load("data/zh_old.rda")
          load("data/wi_old.rda")
          source("data-raw/02_get_updated_data.R")
          source("data-raw/03_prepare_data_for_modules.R")
        shell: Rscript {0}

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          # The committer's email address
          email: ${{ github.actor }}@localhost
          # The committer's name
          name: ${{ github.actor }}
          # The commit message
          message: Automatic data update using GitHub Actions
          # The branch to push the changes back to, defaults to the current branch
          branch: ${{ github.ref }}
          # The files to add separated by space, defaults to every file
          files: .
          # The repository to push the code to, defaults to origin (e.g. this repository)
          repository: origin
          # The token used to push the code, not needed if you push to the same repository
          token:  ${{ secrets.PAT}}
          # Whether to perform force push
          force: 0
          # The working directory that will be used for git commands
          directory: .
