name: Update data

on:
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.PAT}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("curl", "data.table", "dplyr", "fable",
          "fabletools", "feasts", "glue", "htmltools", "janitor", "lubridate",
          "magrittr", "purrr", "tidyr", "tsibble", "usethis"))
        shell: Rscript {0}

      - name: Update data
        run: |
          library(magrittr)
          source("R/utils_data_wrangle.R")
          source("R/utils_get_data.R")
          source("R/utils_module_dataviz.R")
          source("R/utils_module_overview_month.R")
          source("R/utils_module_overview_week.R")
          source("R/utils_module_overview_year.R")
          source("R/utils_module_predictions.R")
          load("data/zh_old.rda")
          load("data/wi_old.rda")
          source("data-raw/02_get_updated_data.R")
          source("data-raw/03_prepare_data_for_modules.R")
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add latest data"
          git push
